// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClKdb3mvdexh3FsO5sR-fa1xGwZgEACNo',
    appId: '1:179479625797:web:4e660566124a01937ba32c',
    messagingSenderId: '179479625797',
    projectId: 'fireb-notes',
    authDomain: 'fireb-notes.firebaseapp.com',
    databaseURL: 'https://fireb-notes-default-rtdb.firebaseio.com',
    storageBucket: 'fireb-notes.appspot.com',
    measurementId: 'G-5PKG47V0YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHhLDemro8UWGRD0GXUmAEbaSaXt_wrhw',
    appId: '1:179479625797:android:42be521b2466447d7ba32c',
    messagingSenderId: '179479625797',
    projectId: 'fireb-notes',
    databaseURL: 'https://fireb-notes-default-rtdb.firebaseio.com',
    storageBucket: 'fireb-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQvklV9opEkmN-hZvqHOOS0AJKbqKUPxM',
    appId: '1:179479625797:ios:8962fa70853ae6977ba32c',
    messagingSenderId: '179479625797',
    projectId: 'fireb-notes',
    databaseURL: 'https://fireb-notes-default-rtdb.firebaseio.com',
    storageBucket: 'fireb-notes.appspot.com',
    iosClientId: '179479625797-lcsr6i9viqpe9raa7qvo5kbd1mdvi56l.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQvklV9opEkmN-hZvqHOOS0AJKbqKUPxM',
    appId: '1:179479625797:ios:f681bf39424f3b3f7ba32c',
    messagingSenderId: '179479625797',
    projectId: 'fireb-notes',
    databaseURL: 'https://fireb-notes-default-rtdb.firebaseio.com',
    storageBucket: 'fireb-notes.appspot.com',
    iosClientId: '179479625797-pr6o9t7lpdkrg8cge6kmkv9kt49s3d4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebNotes.RunnerTests',
  );
}
